click(Pattern("258PM5112012.png").targetOffset(91,0))
click("1339441196477.png")
find("EgEIQSteeliy.png")
click(Pattern("EgEIQSteeliy.png").targetOffset(45,15))
rightClick(Pattern("QSteeliyeDat.png").targetOffset(-35,17))
click(Pattern("CreateJobCon.png").targetOffset(-47,67))
wait("StcclyeDataK-1.png",20)
click(Pattern("StcclyeDataK-1.png").targetOffset(71,47))
wait("SteeiyeDatal-1.png",30)
click(Pattern("SteeiyeDatal-1.png").targetOffset(175,87))
find("5rgFTUTECrea.png")
click(Pattern("5rgFTUTECrea.png").targetOffset(91,-85))
click("Hsu-1.png")
click("ControlPanel.png")
wait("aiNetworkand.png",60)
click("ProgramsUnin.png")
wait("ControlPanel-1.png",60)
click("SteeIEyeData.png")
click("HTH.png")
wait("SteelyeDatal.png",60)
click("Remove1Remov.png")
click("1339097942645.png")
click("1339094489035.png")
wait("SteeEyeDataK.png",60)
click("F.png")
wait("SteelyeDataK.png",60)
click("1339094561578.png")
wait("SteelyeDataK-1.png",60)
click("NoIwillresta.png")
click("BackFinish.png")
click(Pattern("gProgramsand.png").targetOffset(385,-2))
click("fjstan-1.png")
click("Run-1.png")
wait("IRunXTypethe.png",10)
type("cmd" + Key.ENTER)
wait("Admhishaton.png",30)
type("DEL /F /Q C:\DK_Builds\InProgress.xyz" + Key.ENTER)
type("DEL /F /Q C:\DK_Builds\UninstallFlag\UninstallFlag.xyz" + Key.ENTER)
type("Shutdown /r /t 0" + Key.ENTER)






